change test api paths to match new definition
Gamify-IT/run-config pull request #14
Opened 2022-07-25 21:57 UTC by madebyTimo

part of https://github.com/Gamify-IT/issues/issues/166

2022-07-25 21:59 UTC, madebyTimo commented
please not merge before api path change is accepted from and done in overworld-backend

2022-07-25 22:00 UTC, delvh approved these changes

2022-07-25 22:01 UTC, delvh requested changes
I meant of course

2022-07-26 21:19 UTC, madebyTimo commented
It is [done in overworld](https://github.com/Gamify-IT/overworld-backend/blob/6334a90addfed27dd4bc147eec71c76592d6d377/src/main/resources/application.properties#L17). Please remove the blocker.

2022-07-26 22:21 UTC, delvh approved these changes

2022-07-27 09:30 UTC, LeviUniAcc approved these changes

2022-07-27 09:30 UTC, merged